
CREATE DATABASE IF NOT EXISTS growayuassist_pwa CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS health_seeker(
  `health_seeker_id` INT(11)NOT NULL AUTO_INCREMENT COMMENT "HEALTH SEEKER ID",
  `govt_mother_id` INT(11) NULL COMMENT "GOVT MOTHER ID",
  `mother_name` VARCHAR(50) NULL COMMENT "MOTHER NAME",
  `age` INT(11)NULL COMMENT "AGE",
  `contact_number` VARCHAR(50) NULL COMMENT "CONTACT NUMBER",
  `occupation` VARCHAR(50) NULL COMMENT "OCCUPATION",
  `husband_name` VARCHAR(255) NULL COMMENT "HUSBAND NAME",
  `husband_occupation` VARCHAR(255) NULL COMMENT "HUSBAND OCCUPATION",
  PRIMARY KEY(`health_seeker_id`)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS health_parameter(
  `health_parameter_id` INT(11)NOT NULL AUTO_INCREMENT COMMENT "HEALTH PARAMTER ID",
  `visit_date` DATETIME NULL COMMENT "VISIT DATE",
  `Height` VARCHAR(50) NULL COMMENT "HEIGHT",
  `weight` VARCHAR(50) NULL COMMENT "WEIGHT",
  `bp` VARCHAR(50) NULL COMMENT "BLOOD PRESSURE",
  `hemoglobin` VARCHAR(50) NULL COMMENT "HEMOGLOBIN",
  `blood_sugar` VARCHAR(255) NULL COMMENT "BLOOD SUGAR",
  `urine_albumin` VARCHAR(255) NULL COMMENT "URINE ALBUMIN",
  PRIMARY KEY(`health_parameter_id`)
  )ENGINE = InnoDB DEFAULT CHARSET = utf8;